# bet_model.py
# Khmer News 24
# Football Betting Statistical Model
# Version 1
#
# IMPORTANT:
# - This is a statistical model, NOT a guarantee.
# - Probability is an estimate based on available data.
# - Do not use test/demo data as real betting odds.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional
import math


# ============================================================
# SETTINGS
# ============================================================

MIN_MODEL_PROBABILITY = 75.0
MIN_MATCHES_REQUIRED = 5
MAX_RECENT_MATCHES = 10


# ============================================================
# DATA STRUCTURES
# ============================================================

@dataclass
class MatchResult:
    """
    One completed football match.

    Example:
        Arsenal 2 - 1 Chelsea
    """

    home_team: str
    away_team: str

    home_goals: int
    away_goals: int

    # Optional:
    # "H" = Home win
    # "D" = Draw
    # "A" = Away win
    result: Optional[str] = None


@dataclass
class TeamStats:
    """
    Statistical profile of a team.
    """

    team: str

    matches: int = 0

    wins: int = 0
    draws: int = 0
    losses: int = 0

    goals_for: int = 0
    goals_against: int = 0

    home_matches: int = 0
    home_wins: int = 0
    home_draws: int = 0
    home_losses: int = 0

    away_matches: int = 0
    away_wins: int = 0
    away_draws: int = 0
    away_losses: int = 0

    over_15: int = 0
    over_25: int = 0

    btts_yes: int = 0

    clean_sheets: int = 0


@dataclass
class MatchPrediction:
    """
    Prediction generated by the statistical model.
    """

    home_team: str
    away_team: str

    home_win_probability: float
    draw_probability: float
    away_win_probability: float

    over_15_probability: float
    over_25_probability: float

    btts_probability: float

    double_chance_1x_probability: float
    double_chance_x2_probability: float

    best_market: Optional[str] = None
    best_selection: Optional[str] = None
    best_probability: Optional[float] = None

    confidence: str = "LOW"


# ============================================================
# BASIC HELPERS
# ============================================================

def clamp(value: float, minimum: float, maximum: float) -> float:
    """
    Keep value between minimum and maximum.
    """

    return max(minimum, min(value, maximum))


def percentage(value: int, total: int) -> float:
    """
    Convert count into percentage.
    """

    if total <= 0:
        return 0.0

    return round((value / total) * 100, 2)


def safe_average(values: list[float]) -> float:
    """
    Calculate average safely.
    """

    if not values:
        return 0.0

    return sum(values) / len(values)


# ============================================================
# RESULT NORMALIZATION
# ============================================================

def normalize_result(match: MatchResult) -> str:
    """
    Determine result from score.
    """

    if match.home_goals > match.away_goals:
        return "H"

    if match.home_goals < match.away_goals:
        return "A"

    return "D"


# ============================================================
# TEAM STATISTICS
# ============================================================

def calculate_team_stats(
    team: str,
    matches: list[MatchResult],
) -> TeamStats:
    """
    Calculate statistics for one team.

    Only matches involving the requested team are used.
    """

    stats = TeamStats(team=team)

    # Most recent matches first
    recent_matches = matches[-MAX_RECENT_MATCHES:]

    for match in recent_matches:

        is_home = match.home_team.lower() == team.lower()
        is_away = match.away_team.lower() == team.lower()

        if not is_home and not is_away:
            continue

        stats.matches += 1

        total_goals = (
            match.home_goals +
            match.away_goals
        )

        if total_goals >= 2:
            stats.over_15 += 1

        if total_goals >= 3:
            stats.over_25 += 1

        if match.home_goals > 0 and match.away_goals > 0:
            stats.btts_yes += 1

        # ----------------------------------------------------
        # HOME MATCH
        # ----------------------------------------------------

        if is_home:

            stats.home_matches += 1

            stats.goals_for += match.home_goals
            stats.goals_against += match.away_goals

            if match.away_goals == 0:
                stats.clean_sheets += 1

            if match.home_goals > match.away_goals:

                stats.wins += 1
                stats.home_wins += 1

            elif match.home_goals == match.away_goals:

                stats.draws += 1
                stats.home_draws += 1

            else:

                stats.losses += 1
                stats.home_losses += 1

        # ----------------------------------------------------
        # AWAY MATCH
        # ----------------------------------------------------

        elif is_away:

            stats.away_matches += 1

            stats.goals_for += match.away_goals
            stats.goals_against += match.home_goals

            if match.home_goals == 0:
                stats.clean_sheets += 1

            if match.away_goals > match.home_goals:

                stats.wins += 1
                stats.away_wins += 1

            elif match.away_goals == match.home_goals:

                stats.draws += 1
                stats.away_draws += 1

            else:

                stats.losses += 1
                stats.away_losses += 1

    return stats


# ============================================================
# TEAM METRICS
# ============================================================

def win_rate(stats: TeamStats) -> float:

    return percentage(
        stats.wins,
        stats.matches,
    )


def draw_rate(stats: TeamStats) -> float:

    return percentage(
        stats.draws,
        stats.matches,
    )


def loss_rate(stats: TeamStats) -> float:

    return percentage(
        stats.losses,
        stats.matches,
    )


def goals_for_average(stats: TeamStats) -> float:

    if stats.matches <= 0:
        return 0.0

    return round(
        stats.goals_for / stats.matches,
        2,
    )


def goals_against_average(stats: TeamStats) -> float:

    if stats.matches <= 0:
        return 0.0

    return round(
        stats.goals_against / stats.matches,
        2,
    )


def over_15_rate(stats: TeamStats) -> float:

    return percentage(
        stats.over_15,
        stats.matches,
    )


def over_25_rate(stats: TeamStats) -> float:

    return percentage(
        stats.over_25,
        stats.matches,
    )


def btts_rate(stats: TeamStats) -> float:

    return percentage(
        stats.btts_yes,
        stats.matches,
    )


def clean_sheet_rate(stats: TeamStats) -> float:

    return percentage(
        stats.clean_sheets,
        stats.matches,
    )


# ============================================================
# POISSON HELPER
# ============================================================

def poisson_probability(
    goals: int,
    expected_goals: float,
) -> float:
    """
    Poisson probability.

    P(X=k) = e^-lambda * lambda^k / k!
    """

    if expected_goals < 0:
        return 0.0

    try:
        return (
            math.exp(-expected_goals)
            * expected_goals ** goals
            / math.factorial(goals)
        )

    except (OverflowError, ValueError):

        return 0.0


# ============================================================
# EXPECTED GOALS
# ============================================================

def calculate_expected_goals(
    home_stats: TeamStats,
    away_stats: TeamStats,
) -> tuple[float, float]:
    """
    Estimate expected goals.

    Uses:
        - home team's scoring
        - away team's conceding
        - away team's scoring
        - home team's conceding

    This is intentionally a simple first-version model.
    """

    home_scoring = goals_for_average(home_stats)

    home_conceding = goals_against_average(
        home_stats
    )

    away_scoring = goals_for_average(away_stats)

    away_conceding = goals_against_average(
        away_stats
    )

    home_expected = (
        home_scoring +
        away_conceding
    ) / 2

    away_expected = (
        away_scoring +
        home_conceding
    ) / 2

    # Prevent unrealistic values
    home_expected = clamp(
        home_expected,
        0.10,
        4.50,
    )

    away_expected = clamp(
        away_expected,
        0.10,
        4.50,
    )

    return (
        round(home_expected, 3),
        round(away_expected, 3),
    )


# ============================================================
# SCORE MATRIX
# ============================================================

def build_score_matrix(
    home_expected: float,
    away_expected: float,
    max_goals: int = 8,
) -> list[list[float]]:
    """
    Build probability matrix for possible scores.
    """

    matrix = []

    for home_goals in range(max_goals + 1):

        row = []

        home_probability = poisson_probability(
            home_goals,
            home_expected,
        )

        for away_goals in range(max_goals + 1):

            away_probability = poisson_probability(
                away_goals,
                away_expected,
            )

            probability = (
                home_probability *
                away_probability
            )

            row.append(probability)

        matrix.append(row)

    return matrix


# ============================================================
# MARKET PROBABILITIES
# ============================================================

def calculate_market_probabilities(
    home_expected: float,
    away_expected: float,
) -> dict[str, float]:

    matrix = build_score_matrix(
        home_expected,
        away_expected,
    )

    home_win = 0.0
    draw = 0.0
    away_win = 0.0

    over_15 = 0.0
    over_25 = 0.0

    btts = 0.0

    for home_goals, row in enumerate(matrix):

        for away_goals, probability in enumerate(row):

            # 1X2
            if home_goals > away_goals:
                home_win += probability

            elif home_goals == away_goals:
                draw += probability

            else:
                away_win += probability

            # Over 1.5
            if home_goals + away_goals >= 2:
                over_15 += probability

            # Over 2.5
            if home_goals + away_goals >= 3:
                over_25 += probability

            # BTTS
            if home_goals >= 1 and away_goals >= 1:
                btts += probability

    # Normalize
    total = (
        home_win +
        draw +
        away_win
    )

    if total > 0:

        home_win /= total
        draw /= total
        away_win /= total

    return {
        "home_win": round(home_win * 100, 2),
        "draw": round(draw * 100, 2),
        "away_win": round(away_win * 100, 2),
        "over_15": round(over_15 * 100, 2),
        "over_25": round(over_25 * 100, 2),
        "btts": round(btts * 100, 2),
    }


# ============================================================
# FORM ADJUSTMENT
# ============================================================

def calculate_form_strength(
    stats: TeamStats,
) -> float:
    """
    Calculate a simple form score.

    Win = 3 points
    Draw = 1 point
    Loss = 0 points
    """

    if stats.matches <= 0:
        return 50.0

    points = (
        stats.wins * 3 +
        stats.draws
    )

    maximum_points = stats.matches * 3

    if maximum_points <= 0:
        return 50.0

    return (
        points /
        maximum_points
    ) * 100


def form_difference(
    home_stats: TeamStats,
    away_stats: TeamStats,
) -> float:

    home_form = calculate_form_strength(
        home_stats
    )

    away_form = calculate_form_strength(
        away_stats
    )

    return home_form - away_form


# ============================================================
# MATCH PREDICTION
# ============================================================

def predict_match(
    home_team: str,
    away_team: str,
    historical_matches: list[MatchResult],
) -> Optional[MatchPrediction]:
    """
    Generate statistical prediction.

    Requires enough recent data for BOTH teams.
    """

    home_stats = calculate_team_stats(
        home_team,
        historical_matches,
    )

    away_stats = calculate_team_stats(
        away_team,
        historical_matches,
    )

    # Need enough data
    if home_stats.matches < MIN_MATCHES_REQUIRED:
        return None

    if away_stats.matches < MIN_MATCHES_REQUIRED:
        return None

    # Expected goals
    home_expected, away_expected = (
        calculate_expected_goals(
            home_stats,
            away_stats,
        )
    )

    # Poisson probabilities
    probabilities = calculate_market_probabilities(
        home_expected,
        away_expected,
    )

    # --------------------------------------------------------
    # FORM ADJUSTMENT
    # --------------------------------------------------------

    difference = form_difference(
        home_stats,
        away_stats,
    )

    # Small home advantage
    home_advantage = 4.0

    adjustment = (
        difference * 0.05
        + home_advantage
    )

    home_win = (
        probabilities["home_win"]
        + adjustment
    )

    away_win = (
        probabilities["away_win"]
        - adjustment
    )

    draw = probabilities["draw"]

    # Clamp
    home_win = clamp(
        home_win,
        1.0,
        95.0,
    )

    away_win = clamp(
        away_win,
        1.0,
        95.0,
    )

    draw = clamp(
        draw,
        1.0,
        95.0,
    )

    # Normalize 1X2
    total = (
        home_win +
        draw +
        away_win
    )

    home_win = (
        home_win /
        total
    ) * 100

    draw = (
        draw /
        total
    ) * 100

    away_win = (
        away_win /
        total
    ) * 100

    # --------------------------------------------------------
    # DOUBLE CHANCE
    # --------------------------------------------------------

    double_chance_1x = (
        home_win +
        draw
    )

    double_chance_x2 = (
        away_win +
        draw
    )

    # --------------------------------------------------------
    # FIND BEST MARKET
    # --------------------------------------------------------

    markets = {
        "1X": double_chance_1x,
        "X2": double_chance_x2,
        "Over 1.5": probabilities["over_15"],
        "BTTS Yes": probabilities["btts"],
    }

    best_market = max(
        markets,
        key=markets.get,
    )

    best_probability = markets[
        best_market
    ]

    # Selection
    if best_market == "1X":
        best_selection = "1X"

    elif best_market == "X2":
        best_selection = "X2"

    elif best_market == "Over 1.5":
        best_selection = "Over 1.5"

    else:
        best_selection = "BTTS Yes"

    # Confidence
    if best_probability >= 85:
        confidence = "HIGH"

    elif best_probability >= 75:
        confidence = "MEDIUM-HIGH"

    elif best_probability >= 65:
        confidence = "MEDIUM"

    else:
        confidence = "LOW"

    return MatchPrediction(
        home_team=home_team,
        away_team=away_team,

        home_win_probability=round(
            home_win,
            2,
        ),

        draw_probability=round(
            draw,
            2,
        ),

        away_win_probability=round(
            away_win,
            2,
        ),

        over_15_probability=round(
            probabilities["over_15"],
            2,
        ),

        over_25_probability=round(
            probabilities["over_25"],
            2,
        ),

        btts_probability=round(
            probabilities["btts"],
            2,
        ),

        double_chance_1x_probability=round(
            double_chance_1x,
            2,
        ),

        double_chance_x2_probability=round(
            double_chance_x2,
            2,
        ),

        best_market=best_market,
        best_selection=best_selection,
        best_probability=round(
            best_probability,
            2,
        ),

        confidence=confidence,
    )


# ============================================================
# 75% FILTER
# ============================================================

def qualifies_for_accumulator(
    prediction: MatchPrediction,
    minimum_probability: float = MIN_MODEL_PROBABILITY,
) -> bool:
    """
    Check whether prediction reaches
    the ACC probability threshold.
    """

    if prediction.best_probability is None:
        return False

    return (
        prediction.best_probability
        >= minimum_probability
    )


# ============================================================
# FORMAT PREDICTION
# ============================================================

def format_prediction(
    prediction: MatchPrediction,
) -> str:

    return (
        f"⚽ {prediction.home_team} "
        f"vs {prediction.away_team}\n"
        f"\n"
        f"🏠 1: "
        f"{prediction.home_win_probability:.1f}%\n"
        f"🤝 X: "
        f"{prediction.draw_probability:.1f}%\n"
        f"✈️ 2: "
        f"{prediction.away_win_probability:.1f}%\n"
        f"\n"
        f"📈 Over 1.5: "
        f"{prediction.over_15_probability:.1f}%\n"
        f"📈 Over 2.5: "
        f"{prediction.over_25_probability:.1f}%\n"
        f"⚽ BTTS: "
        f"{prediction.btts_probability:.1f}%\n"
        f"\n"
        f"🎯 Best Market: "
        f"{prediction.best_market}\n"
        f"📌 Pick: "
        f"{prediction.best_selection}\n"
        f"🤖 Model: "
        f"{prediction.best_probability:.1f}%\n"
        f"📊 Confidence: "
        f"{prediction.confidence}"
    )


# ============================================================
# FIND ACCUMULATOR CANDIDATES
# ============================================================

def find_accumulator_candidates(
    predictions: list[MatchPrediction],
    minimum_probability: float = MIN_MODEL_PROBABILITY,
) -> list[MatchPrediction]:
    """
    Return only predictions that pass
    the model probability threshold.
    """

    candidates = []

    for prediction in predictions:

        if qualifies_for_accumulator(
            prediction,
            minimum_probability,
        ):
            candidates.append(prediction)

    # Highest probability first
    candidates.sort(
        key=lambda x: x.best_probability or 0,
        reverse=True,
    )

    return candidates


# ============================================================
# DEMO / TEST DATA
# ============================================================

def create_demo_matches() -> list[MatchResult]:
    """
    Demo data ONLY.

    This is NOT live football data.
    """

    return [

        MatchResult(
            "Arsenal",
            "Chelsea",
            2,
            0,
        ),

        MatchResult(
            "Chelsea",
            "Liverpool",
            1,
            2,
        ),

        MatchResult(
            "Manchester City",
            "Arsenal",
            2,
            1,
        ),

        MatchResult(
            "Arsenal",
            "Manchester United",
            3,
            1,
        ),

        MatchResult(
            "Tottenham",
            "Arsenal",
            1,
            2,
        ),

        MatchResult(
            "Chelsea",
            "Arsenal",
            0,
            2,
        ),

        MatchResult(
            "Arsenal",
            "Liverpool",
            2,
            2,
        ),

        MatchResult(
            "Manchester United",
            "Arsenal",
            0,
            3,
        ),

        MatchResult(
            "Arsenal",
            "Tottenham",
            2,
            1,
        ),

        MatchResult(
            "Liverpool",
            "Arsenal",
            1,
            1,
        ),

        # Chelsea additional matches

        MatchResult(
            "Chelsea",
            "Everton",
            2,
            0,
        ),

        MatchResult(
            "Newcastle",
            "Chelsea",
            1,
            1,
        ),

        MatchResult(
            "Chelsea",
            "West Ham",
            3,
            1,
        ),

        MatchResult(
            "Aston Villa",
            "Chelsea",
            2,
            2,
        ),

        MatchResult(
            "Chelsea",
            "Brighton",
            2,
            1,
        ),
    ]


# ============================================================
# TEST
# ============================================================

def test_model():

    print("=" * 60)
    print("KHMER NEWS 24 - BET MODEL TEST")
    print("=" * 60)

    historical_matches = create_demo_matches()

    prediction = predict_match(
        home_team="Arsenal",
        away_team="Chelsea",
        historical_matches=historical_matches,
    )

    if prediction is None:

        print()
        print(
            "❌ Not enough historical data."
        )

        return

    print()
    print(
        format_prediction(
            prediction
        )
    )

    print()
    print("=" * 60)

    if qualifies_for_accumulator(
        prediction
    ):

        print(
            "✅ QUALIFIED FOR ACC "
            "(Model probability >= 75%)"
        )

    else:

        print(
            "❌ NOT QUALIFIED FOR ACC"
        )

    print("=" * 60)

    print()
    print(
        "⚠️ DEMO DATA ONLY"
    )

    print(
        "Do NOT use this test output "
        "as real betting advice."
    )


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    test_model()

# ============================================================
# REAL DATA TEST
# ============================================================

def test_real_football_data():
    """
    Test:
        TheSportsDB
            ↓
        football_data.py
            ↓
        bet_model.py

    This uses real completed match data.
    """

    print()
    print("=" * 60)
    print("REAL FOOTBALL DATA → BET MODEL")
    print("=" * 60)

    try:
        from football_data import (
            get_league_results,
            convert_to_model_data,
        )

    except Exception as error:

        print()
        print(
            "❌ Cannot import football_data.py"
        )

        print(
            f"Error: {error}"
        )

        return

    # --------------------------------------------------------
    # Get real Premier League results
    # --------------------------------------------------------

    print()
    print(
        "📡 Loading Premier League data..."
    )

    football_matches = get_league_results(
        "Premier League"
    )

    if not football_matches:

        print()
        print(
            "❌ No football data received."
        )

        return

    print()
    print(
        f"✅ Received "
        f"{len(football_matches)} matches."
    )

    # --------------------------------------------------------
    # Convert to bet_model format
    # --------------------------------------------------------

    historical_matches = (
        convert_to_model_data(
            football_matches
        )
    )

    print(
        f"✅ Converted "
        f"{len(historical_matches)} "
        f"matches for model."
    )

    # --------------------------------------------------------
    # Find available teams
    # --------------------------------------------------------

    teams = set()

    for match in historical_matches:

        teams.add(
            match.home_team
        )

        teams.add(
            match.away_team
        )

    print()
    print(
        f"⚽ Teams found: "
        f"{len(teams)}"
    )

    # --------------------------------------------------------
    # Show teams
    # --------------------------------------------------------

    print()

    for team in sorted(teams):

        print(
            f"• {team}"
        )

    # --------------------------------------------------------
    # Test prediction
    #
    # Use first available matchup
    # from the real data.
    # --------------------------------------------------------

    if not historical_matches:

        print(
            "❌ No historical matches."
        )

        return

    first_match = (
        historical_matches[0]
    )

    home_team = (
        first_match.home_team
    )

    away_team = (
        first_match.away_team
    )

    print()
    print("=" * 60)

    print(
        "🧪 TEST MATCH"
    )

    print(
        f"⚽ {home_team} "
        f"vs {away_team}"
    )

    print("=" * 60)

    # --------------------------------------------------------
    # IMPORTANT:
    #
    # The first match itself is included in the historical
    # dataset. This is only a connection test.
    #
    # For proper backtesting we will later remove future/
    # same-match information.
    # --------------------------------------------------------

    prediction = predict_match(
        home_team=home_team,
        away_team=away_team,
        historical_matches=historical_matches,
    )

    if prediction is None:

        print()
        print(
            "⚠️ Not enough historical data "
            "for both teams."
        )

        print(
            "This is normal if the free "
            "data source returned too few "
            "matches."
        )

        return

    print()

    print(
        format_prediction(
            prediction
        )
    )

    print()
    print("=" * 60)

    # --------------------------------------------------------
    # ACC FILTER
    # --------------------------------------------------------

    if qualifies_for_accumulator(
        prediction,
        minimum_probability=75.0,
    ):

        print(
            "🎯 ACC CANDIDATE"
        )

        print(
            "✅ Model probability >= 75%"
        )

    else:

        print(
            "❌ Not an ACC candidate"
        )

        print(
            "Model probability < 75%"
        )

    print("=" * 60)

    print()
    print(
        "⚠️ This is statistical analysis."
    )

    print(
        "It does NOT guarantee a match result."
    )
    # ============================================================
# PROPER BACKTEST V1
# ============================================================

def backtest_model(
    matches,
    minimum_probability=75.0,
):
    """
    Simple chronological backtest.

    The model only uses matches BEFORE the match
    being tested.

    This helps avoid future-data leakage.
    """

    print()
    print("=" * 60)
    print("📊 BET MODEL BACKTEST")
    print("=" * 60)

    if not matches:
        print("❌ No matches.")
        return

    # Sort chronologically
    sorted_matches = sorted(
        matches,
        key=lambda x: (
            getattr(x, "date", "") or ""
        )
    )

    total_predictions = 0
    qualified_predictions = 0
    correct_predictions = 0

    results = []

    # Start after enough historical matches
    for index in range(
        MIN_MATCHES_REQUIRED,
        len(sorted_matches),
    ):

        current = sorted_matches[index]

        # Only data BEFORE current match
        historical = sorted_matches[:index]

        prediction = predict_match(
            home_team=current.home_team,
            away_team=current.away_team,
            historical_matches=historical,
        )

        if prediction is None:
            continue

        total_predictions += 1

        if not qualifies_for_accumulator(
            prediction,
            minimum_probability,
        ):
            continue

        qualified_predictions += 1

        # ----------------------------------------------------
        # Determine model prediction
        # ----------------------------------------------------

        pick = prediction.best_selection

        actual_home = current.home_goals
        actual_away = current.away_goals

        if pick == "1X":

            correct = (
                actual_home >= actual_away
            )

        elif pick == "X2":

            correct = (
                actual_away >= actual_home
            )

        elif pick == "Over 1.5":

            correct = (
                actual_home +
                actual_away
                >= 2
            )

        elif pick == "BTTS Yes":

            correct = (
                actual_home >= 1
                and
                actual_away >= 1
            )

        else:

            correct = False

        if correct:
            correct_predictions += 1

        results.append({
            "home": current.home_team,
            "away": current.away_team,
            "pick": pick,
            "probability": (
                prediction.best_probability
            ),
            "actual": (
                f"{actual_home}-{actual_away}"
            ),
            "correct": correct,
        })

    # ========================================================
    # RESULTS
    # ========================================================

    print()

    print(
        f"📌 Model predictions: "
        f"{total_predictions}"
    )

    print(
        f"🎯 Qualified ≥ "
        f"{minimum_probability}%: "
        f"{qualified_predictions}"
    )

    print(
        f"✅ Correct: "
        f"{correct_predictions}"
    )

    if qualified_predictions > 0:

        hit_rate = (
            correct_predictions /
            qualified_predictions
        ) * 100

        print()
        print(
            f"📈 Historical Hit Rate: "
            f"{hit_rate:.2f}%"
        )

    else:

        hit_rate = 0.0

        print()
        print(
            "⚠️ No qualified predictions."
        )

    print()
    print("=" * 60)

    # ========================================================
    # LAST 10 QUALIFIED PREDICTIONS
    # ========================================================

    print(
        "LAST QUALIFIED PREDICTIONS"
    )

    print("=" * 60)

    for item in results[-10:]:

        status = (
            "✅"
            if item["correct"]
            else "❌"
        )

        print(
            f"{status} "
            f"{item['home']} vs "
            f"{item['away']}"
        )

        print(
            f"   Pick: {item['pick']}"
        )

        print(
            f"   Model: "
            f"{item['probability']:.1f}%"
        )

        print(
            f"   Result: "
            f"{item['actual']}"
        )

        print()

    return {
        "total_predictions":
            total_predictions,

        "qualified_predictions":
            qualified_predictions,

        "correct_predictions":
            correct_predictions,

        "hit_rate":
            round(hit_rate, 2),
    }


# ============================================================
# REAL DATA BACKTEST
# ============================================================

def test_real_backtest():

    print()
    print(
        "📡 Loading real football data..."
    )

    try:

        from football_data import (
            get_league_results,
            convert_to_model_data,
        )

    except Exception as error:

        print(
            "❌ Cannot import "
            "football_data.py"
        )

        print(
            f"Error: {error}"
        )

        return

    # --------------------------------------------------------
    # Start with Premier League only
    # --------------------------------------------------------

    matches = get_league_results(
        "Premier League"
    )

    if not matches:

        print(
            "❌ No Premier League data."
        )

        return

    model_matches = (
        convert_to_model_data(
            matches
        )
    )

    print(
        f"✅ Loaded "
        f"{len(model_matches)} "
        f"matches."
    )

    # --------------------------------------------------------
    # Run backtest
    # --------------------------------------------------------

    return backtest_model(
        model_matches,
        minimum_probability=75.0,
    )


# ============================================================
# RUN BACKTEST
# ============================================================

if __name__ == "__main__":
    test_real_backtest()